### PR TITLE
Fix Firebase migration

### LINKED ISSUE #294: Bug in 0.3.1 release: unable to load firebase database
This is due to the update process that crashes.

### PR DESCRIPTION
**Pull request by DavBfr**
Closes #294

### CODE REVIEW

**Comment by baylessj** [comment]
Does this change roll back the version number?

**Comment by DavBfr** [comment]
Still something wrong, I'll provide a fix.

**Comment by DavBfr** [comment]
In lib/blocs/src/cars/bloc.dart I have this:

Screen Shot 2020-03-31 at 15 47 05

**Comment by baylessj** [comment]
Ah yeah, I think I remember seeing that from time to time. Don't remember it actually causing a crash though. 

Should be able to provide an `onError` param to the reduce function or similar and fix it that way

**Comment by DavBfr** [comment]
I pushed some more fixes, see what you think.

It restores the unit tests and fixes the Sembast version info. The version info cannot be changed after the database has been opened. It's a parameter for open() and calls a callback in case the version is different from the database version. Same as Sqlite.

I had to rewrite a big part of the class

**Comment by DavBfr** [comment]
Something still wrong:

00:48 +117 -1: /home/runner/work/autodo/autodo/test/models/repeat_interval_test.dart: repeat interval addToDate [E***                                                                                    
  Expected: DateTime:<1971-02-01 00:00:00.000>
    Actual: DateTime:<1971-02-02 00:00:00.000>
  
  package:test_api                                   expect
  package:flutter_test/src/widget_tester.dart 348:3  expect
  models/repeat_interval_test.dart 9:7               main.<fn>.<fn>

But I don't have this error on my machine, maybe a timezone issue.

**Comment by baylessj** [comment]
Yeah that sounds like a timezone issue to me, didn't see that behavior on my machine. Probably need a .toUtc() call somewhere in the addition

**Pull request merged**
