### PR TITLE
222 add option for changing units

### LINKED ISSUE #222: Add option for changing units
a lot of things are hardcoded as miles. User has requested that it be possible to use metric units.

### PR DESCRIPTION
**Pull request by DavBfr**
It's not totally finished, but already too big.
Missing:
* mpg and ml/days in the reports.
* The stored units are not SI but still US measures for now.

Closes #222

### CODE REVIEW

**Comment by baylessj** [comment]
The implementation looks really good, I like the way that you set this up architecturally much better than my start in the other 222 branch. 

A couple of questions/concerns with the todos that you noted in the OP:
- Will the lack of mpg and mi/day unit support for the charts break them for now? If not then I'm okay with deferring those changes to a later release, but if this will break the charts view then it needs to happen for 0.3.1
- This migration _should_ be straightforward to do, but I've never done a migration with firebase before. My biggest concern is figuring out how to do this migration without assuming that all users update as soon as the update goes out to the app store.

I normally don't pay a ton of attention to the codecov actions, but I would like to see some unit tests for this PR. I find that the unit tests are helpful as simple examples of using libraries and complex functionality like this :smile: 

I ran into one error when trying this out locally, I got the following exception when trying to access the Settings screen. On Android with trial account (local db).

```
I/flutter (22400): Another exception was thrown: A RenderFlex overflowed by 3.0 pixels on the right.
D/ViewRootImpl@1dc3a21[MainActivity](22400): ViewPostIme pointer 0
D/ViewRootImpl@1dc3a21[MainActivity](22400): ViewPostIme pointer 1
D/ViewRootImpl@1dc3a21[MainActivity](22400): ViewPostIme pointer 0
D/ViewRootImpl@1dc3a21[MainActivity](22400): ViewPostIme pointer 1
I/System.out(22400): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(22400): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(22400): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(22400): (HTTPLog)-Static: isSBSettingEnabled false
I/flutter (22400): Another exception was thrown: Trailing widget consumes entire tile width. Please use a sized widget.
I/flutter (22400): Another exception was thrown: RenderBox was not laid out: _RenderListTile#29d2d relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (22400): Another exception was thrown: RenderBox was not laid out: RenderPadding#7f223 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (22400): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#ba7c9 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (22400): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#245c2 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (22400): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#b40e1 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (22400): Another exception was thrown: RenderBox was not laid out: RenderMouseRegion#b090c relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (22400): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#cc2f9 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (22400): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#b6189 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (22400): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 549 pos 12: 'child.hasSize': is not true.
I/flutter (22400): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter (22400): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter (22400): Another exception was thrown: A RenderFlex overflowed by 3.0 pixels on the right.
I/flutter (22400): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
D/ViewRootImpl@1dc3a21[MainActivity](22400): ViewPostIme pointer 0
E/flutter (22400): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'visible' was called on null.
E/flutter (22400): Receiver: null
E/flutter (22400): Tried calling: visible
E/flutter (22400): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (22400): #1      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:636:27)
E/flutter (22400): #2      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #3      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #5      RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3120:31)
E/flutter (22400): #6      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #7      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #8      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #9      RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:166:19)
E/flutter (22400): #10     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #12     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #13     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:166:19)
E/flutter (22400): #14     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #16     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #17     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #18     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #19     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:508:18)
E/flutter (22400): #20     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #21     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #23     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2495:24)
E/flutter (22400): #24     BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:808:31)
E/flutter (22400): #25     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:765:12)
E/flutter (22400): #26     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2490:33)
E/flutter (22400): #27     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:409:12)
E/flutter (22400): #28     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #29     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #30     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #31     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #32     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #33     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1766:18)
E/flutter (22400): #34     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #35     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #36     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #37     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #38     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #39     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #40     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3120:31)
E/flutter (22400): #41     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:119:19)
E/flutter (22400): #42     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2142:11)
E/flutter (22400): #43     Ren
```

**Comment by DavBfr** [comment]
I had no crache on Android or iOS with a fresh install. I fixed the size issue and added Unit tests.

**Comment by DavBfr** [comment]
The missing mpg and mi/day units will not change anything. I'm still struggling to have this working correctly. I think I'll have to generate some historical data to see something.
The migration should be fine, we just need a flag to know if the migration has been done. I'm more worried about floating number precision that could give some wired numbers.

**Comment by baylessj** [comment]
The floating number precision shouldn't be too big of a deal for now, as long as it doesn't cause any wildly incorrect numbers then I'm cool with shipping it. Glad that you've pointed it out so we have a reference point if it bites us in the future, but there are higher priority things to work on now I think. 

I'll run a clean install with your latest changes and see if I still end up hitting that error on the settings screen.

**Pull request merged**
